import { v4 as uuidv4 } from "uuid";
export const AppState = {
  route: window.location.pathname,
  form: {
    lastname: {
      id: uuidv4(),
      type: "input",
      input_type: "text",
      col: "6",
      label: "Nom",
      name: "lastname",
      value: "",
      description: "Saisissez votre nom",
      error: null,
      isRequired: true,
    },
    firstname: {
      id: uuidv4(),
      type: "input",
      input_type: "text",
      col: "6",
      label: "Prénom",
      name: "firstname",
      value: "",
      description: "Saisissez votre prénom",
      error: null,
      isRequired: true,
    },
    email: {
      id: uuidv4(),
      type: "input",
      input_type: "text",
      col: "6",
      label: "Email",
      name: "email",
      value: "",
      description: "Saisissez votre email",
      error: null,
      isRequired: true,
    },
    phone: {
      id: uuidv4(),
      type: "input",
      input_type: "text",
      col: "6",
      label: "Téléphone",
      name: "phone",
      value: "",
      description: "Saisissez votre téléphone",
      error: null,
      isRequired: false,
    },
    message: {
      id: uuidv4(),
      type: "textarea",
      input_type: "textarea",
      col: "12",
      label: "Message",
      name: "message",
      value: "",
      description: "Saisissez votre message",
      error: null,
      isRequired: true,
    },
  },
  loading: false,
  success: null,
  errors: null,
};
